/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.departamentosCategoriasMantenimiento;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import negocio.DepartamentoControl;

/**
 *
 * @author paulp
 */
public class FrmNuevoDepartamento extends javax.swing.JDialog {

    private String accion;
    private DepartamentoControl CONTROL;
    private String departamento_nombre;
    private int departamento_id;
    private int categoria_id;
    /**
     * Creates new form FrmNuevoDepartamento
     */
    public FrmNuevoDepartamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CONTROL = new DepartamentoControl();
        this.accion = accion;
        this.setSize(360, 180);
        this.datos(departamento_id, departamento_nombre, categoria_id, accion);
    }
    
    public void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    public void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void datos(int departamento_id, String departamento_nombre, int categoria_id, String accion){
        this.departamento_id = departamento_id;
        this.departamento_nombre = departamento_nombre;
        this.categoria_id = categoria_id;
        this.accion = accion;
        txtNuevoDepartamento.setText(departamento_nombre);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNuevoDepartamento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Departamento");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtNuevoDepartamento.setPreferredSize(new java.awt.Dimension(180, 20));
        txtNuevoDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNuevoDepartamentoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel1.add(txtNuevoDepartamento, gridBagConstraints);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(btnGuardar, gridBagConstraints);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (accion.equals("insertar")) {
            if (txtNuevoDepartamento.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Debes ingresar un nuevo Departamento, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
                txtNuevoDepartamento.requestFocus();
                return;
            }
            
            String resp;
            resp = this.CONTROL.insertar(txtNuevoDepartamento.getText(),1);
            if (resp.equals("OK")) {
                this.mensajeOk("Registrado Correctamente");
            } else {
                this.mensajeError("No se pudo registrar");
            }
        } else {
            if (accion.equals("editar")) {
                
                if (txtNuevoDepartamento.getText().length() == 0) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un nuevo Departamento","Sistema", JOptionPane.WARNING_MESSAGE);
                    txtNuevoDepartamento.requestFocus();
                    return;
                }
                String resp;
                resp = this.CONTROL.actualizar(departamento_id, txtNuevoDepartamento.getText(), departamento_nombre, categoria_id);
                if (resp.equals("OK")) {
                    
                    this.mensajeOk("Actualizado Correctamente");
                } else {
                    this.mensajeError("No se pudo Actualizar");
                }

            }
        }
        this.dispose();
        FrmSeleccionarDepartamento.btnListar.doClick();
        FrmDepartamentoCategoria.btnListar.doClick();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNuevoDepartamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevoDepartamentoKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtNuevoDepartamentoKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNuevoDepartamento dialog = new FrmNuevoDepartamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNuevoDepartamento;
    // End of variables declaration//GEN-END:variables
}
