/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.departamentosCategoriasMantenimiento;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import negocio.CategoriaControl;
import negocio.DepartamentoControl;

/**
 *
 * @author paulp
 */
public class FrmNuevoDepartamentoCategoria extends javax.swing.JDialog {

    private CategoriaControl CONTROL;
    private DepartamentoControl CONTROLD;
    private String accion;
    private int departamento_id;
    private String departamento_nombre;
    private int categoria_id;
    private String categoria_nombre;

    /**
     * Creates new form FrmNuevorDepartamentoCategoria
     */
    public FrmNuevoDepartamentoCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CONTROL = new CategoriaControl();
        CONTROLD = new DepartamentoControl();
        this.setSize(360, 180);
        this.datos(departamento_id, departamento_nombre, categoria_id, categoria_nombre, accion);
        txtDepartamento.setEditable(false);
        setLocationRelativeTo(null);
    }

    public void datos(int departamento_id, String departamento_nombre, int categoria_id, String categoria_nombre, String accion) {
        this.departamento_id = departamento_id;
        this.departamento_nombre = departamento_nombre;
        this.categoria_id = categoria_id;
        this.categoria_nombre = categoria_nombre;
        this.accion = accion;
        txtDepartamento.setText(departamento_nombre);
        txtCategoria.setText(categoria_nombre);
    }

    public void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    public void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        btnSeleccionarDepartamento = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione el Departamento y la Categoria");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Departamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtDepartamento.setPreferredSize(new java.awt.Dimension(180, 20));
        txtDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDepartamentoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 5);
        jPanel1.add(txtDepartamento, gridBagConstraints);

        jLabel2.setText("Categoria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtCategoria.setPreferredSize(new java.awt.Dimension(180, 20));
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(txtCategoria, gridBagConstraints);

        btnSeleccionarDepartamento.setText("...");
        btnSeleccionarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarDepartamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel1.add(btnSeleccionarDepartamento, gridBagConstraints);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(btnGuardar, gridBagConstraints);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarDepartamentoActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        FrmSeleccionarDepartamento frm = new FrmSeleccionarDepartamento(f, true);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarDepartamentoActionPerformed

    private void txtDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDepartamentoMouseClicked
        if (evt.getClickCount() == 2) {
            btnSeleccionarDepartamento.doClick();
        }
    }//GEN-LAST:event_txtDepartamentoMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (accion.equals("insertar")) {
            if (txtDepartamento.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Debes ingresar un Departamento, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
                txtDepartamento.requestFocus();
                return;
            }

            if (txtCategoria.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Debes ingresar una Categoria, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
                txtCategoria.requestFocus();
                return;
            }

            String resp;
            resp = this.CONTROL.insertar(txtCategoria.getText(), txtDepartamento.getText());
            if (resp.equals("OK")) {
                this.mensajeOk("Registrado Correctamente");
            } else {
                this.mensajeError("No se pudo registrar");
            }
        } else {
            if (accion.equals("editar")) {
                if (txtDepartamento.getText().length() == 0) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un Departamento, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
                    txtDepartamento.requestFocus();
                    return;
                }

                if (txtCategoria.getText().length() == 0) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar una Categoria, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
                    txtCategoria.requestFocus();
                    return;
                }

                String resp;
                String resp2;
                if(categoria_id == 1){
                    resp = this.CONTROL.insertar(txtCategoria.getText(), txtDepartamento.getText());
                }else {
                    resp = this.CONTROL.actualizar(categoria_id, txtCategoria.getText(), categoria_nombre);
                }
                if (resp.equals("OK")) {
                    resp2 = this.CONTROLD.actualizar(departamento_id, txtDepartamento.getText(), departamento_nombre, categoria_id);
                    if(resp2.equals("OK")){
                        this.mensajeOk("Actualizado Correctamente");
                    }
                } else {
                    this.mensajeError("No se pudo Actualizar");
                }

            }
        }
        FrmDepartamentoCategoria.btnListar.doClick();
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtCategoriaKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamentoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamentoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamentoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoDepartamentoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNuevoDepartamentoCategoria dialog = new FrmNuevoDepartamentoCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSeleccionarDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JTextField txtCategoria;
    protected static javax.swing.JTextField txtDepartamento;
    // End of variables declaration//GEN-END:variables
}
